export type Skill = "listening" | "reading" | "writing" | "speaking";
export const skillNames: Record<Skill, string> = {
  listening: "Listening",
  reading: "Reading",
  writing: "Writing",
  speaking: "Speaking",
};
export type Question = {
  id: string;
  text: string;
  options: string[];
  answer: number;
  explanation: string;
  tag: string;
};
export type Lesson = {
  id: string;
  version: number;
  skill: Skill;
  title: string;
  subtitle: string;
  topic: string;
  level: "B1" | "B2";
  minutes: number;
  part: string;
  text: string;
  questions: Question[];
  tips: string[];
  minWords?: number;
  sample?: string;
};
const q = (
  id: string,
  text: string,
  options: string[],
  answer: number,
  explanation: string,
  tag = "Thông tin chi tiết",
): Question => ({ id, text, options, answer, explanation, tag });
const lessonDefinitions: Omit<Lesson, "version">[] = [
  {
    id: "reading-cafe",
    skill: "reading",
    title: "A little café, a bigger change",
    subtitle: "Tìm ý chính và thông tin chi tiết",
    topic: "Cuộc sống Sài Gòn",
    level: "B1",
    minutes: 10,
    part: "Đọc hiểu • Bài ngắn",
    text: `When Linh opened her café in Ho Chi Minh City, she expected most customers to buy a drink and leave. Instead, students began staying for hours, sharing tables and working on group projects. Some asked for quieter music; others wanted more power sockets. Linh realised that she was offering more than coffee: she was providing a place to learn.\n\nShe decided to reserve the upstairs room for quiet study between two and six in the afternoon. Customers could book a seat online, but they did not have to pay an extra fee. They only needed to order one drink. At first, Linh worried that people staying longer would reduce her income. However, many visitors returned regularly and recommended the café to their friends.\n\nNot everyone welcomed the change. A group of regular customers missed the lively conversations upstairs. Rather than ask them to leave, Linh arranged a weekly language exchange on the ground floor. On Thursday evenings, learners could practise English with one another. There was no teacher and no formal lesson; each table received a few conversation topics.\n\nAfter three months, the café was busier on weekdays, which had previously been its quietest period. Linh had not increased drink prices or spent money on advertising. She believes that listening to customers helped her more than following a complicated business plan. Her next step is to invite local book clubs, although she wants to keep some evenings free for ordinary visitors.`,
    questions: [
      q(
        "rc1",
        "What is the main purpose of the passage?",
        [
          "To explain how to make better coffee",
          "To describe how a café adapted to its customers",
          "To compare studying at home and at school",
          "To advertise a new language course",
        ],
        1,
        "Cả bài kể quá trình Linh điều chỉnh không gian theo nhu cầu khách: phòng học yên tĩnh và buổi trao đổi ngôn ngữ.",
        "Ý chính",
      ),
      q(
        "rc2",
        "What must customers do to use the study room?",
        [
          "Pay an hourly charge",
          "Join a book club",
          "Buy a drink",
          "Attend an English lesson",
        ],
        2,
        "Đoạn 2: “They only needed to order one drink.” Không có phí bổ sung.",
      ),
      q(
        "rc3",
        "Why did Linh organise a language exchange?",
        [
          "To offer a social activity for customers who liked conversation",
          "To replace the quiet study room",
          "To train new teachers",
          "To attract only foreign tourists",
        ],
        0,
        "Khách cũ nhớ không khí trò chuyện nên Linh bố trí buổi giao lưu ở tầng trệt.",
        "Suy luận",
      ),
      q(
        "rc4",
        "The word “regularly” is closest in meaning to:",
        ["Immediately", "Secretly", "Rarely", "Frequently"],
        3,
        "“Returned regularly” là quay lại thường xuyên, gần nghĩa với frequently.",
        "Từ vựng trong ngữ cảnh",
      ),
      q(
        "rc5",
        "Which statement about the café is true?",
        [
          "It raised prices after three months",
          "It became busier during the week",
          "It now employs an English teacher",
          "It stopped serving ordinary visitors",
        ],
        1,
        "Đoạn cuối nói quán đông hơn vào các ngày trong tuần; giá không tăng.",
      ),
    ],
    tips: [
      "Đọc câu hỏi trước để biết thông tin cần tìm.",
      "Ý chính phải bao quát toàn bài, không chỉ một chi tiết thú vị.",
    ],
  },
  {
    id: "reading-commute",
    skill: "reading",
    title: "Rethinking the daily commute",
    subtitle: "Nhận diện quan điểm và suy luận",
    topic: "Giao thông",
    level: "B2",
    minutes: 12,
    part: "Đọc hiểu • Bài ngắn",
    text: `For years, urban planners assumed that adding more roads would solve congestion. Yet in many cities, new roads have filled almost as quickly as they were built. Transport researchers call this induced demand: when driving becomes easier, more people choose to drive. A lasting solution, they argue, requires attractive alternatives rather than simply more space for cars.\n\nPublic transport is often presented as that alternative. However, affordability alone does not persuade everyone to switch. A commuter who can afford a cheap bus ticket may still ride a motorbike if the bus arrives unpredictably. Reliability and convenient connections can matter more than a small reduction in fares. A journey that looks short on a map may become impractical when it requires two long waits.\n\nSome employers have tried a different approach by allowing flexible starting times. Employees can avoid the busiest hour without changing how they travel. This reduces pressure at peak times, but it cannot help workers whose jobs require a fixed schedule. Retail assistants, for example, generally need to be present when a shop opens.\n\nCycling infrastructure offers another possibility. A painted line on a busy road, though inexpensive, may do little to reassure a nervous cyclist. Connected lanes separated from traffic are more likely to encourage people who do not already cycle. Such projects require both money and street space, which can make them politically difficult.\n\nNo single measure can serve every commuter. The most promising strategies combine reliable public transport, safer walking and cycling routes, and flexible working arrangements where possible. Success should be measured not by how fast cars move, but by how easily people can reach the places that matter to them.`,
    questions: [
      q(
        "rt1",
        "What does “induced demand” refer to?",
        [
          "People avoiding new roads",
          "Road improvements encouraging more driving",
          "A reduction in the number of commuters",
          "Higher prices for private vehicles",
        ],
        1,
        "Đoạn 1 giải thích: đường dễ đi hơn khiến nhiều người chọn lái xe hơn.",
      ),
      q(
        "rt2",
        "Why might cheap bus fares fail to attract a commuter?",
        [
          "Buses cannot enter cities",
          "The commuter prefers walking",
          "The service may be unreliable",
          "Employers pay all travel costs",
        ],
        2,
        "Giá rẻ không bù được thời gian chờ và lịch xe khó dự đoán.",
      ),
      q(
        "rt3",
        "Retail assistants are mentioned to illustrate:",
        [
          "The limitations of flexible working hours",
          "The benefits of cheaper bus tickets",
          "The importance of online shopping",
          "A group that usually cycles to work",
        ],
        0,
        "Người bán hàng phải có mặt lúc mở cửa, nên không phải ai cũng được đổi giờ làm.",
        "Mục đích tác giả",
      ),
      q(
        "rt4",
        "Which cycling measure does the author consider more effective?",
        [
          "Wider parking spaces",
          "Lower bicycle prices",
          "Painted lines without connections",
          "Connected lanes separated from traffic",
        ],
        3,
        "Tác giả so sánh vạch sơn với làn liên thông tách khỏi xe cơ giới.",
      ),
      q(
        "rt5",
        "What is the author’s overall position?",
        [
          "Cities should focus exclusively on buses",
          "An integrated approach is needed",
          "Road construction must stop everywhere",
          "Commuters should all work from home",
        ],
        1,
        "Đoạn kết ủng hộ kết hợp nhiều giải pháp theo nhu cầu khác nhau.",
        "Quan điểm tác giả",
      ),
    ],
    tips: [
      "Tìm từ nối “however”, “yet”, “though” để nhận ra giới hạn của một ý.",
      "Tránh đáp án tuyệt đối có “all”, “only”, “everywhere” nếu bài không khẳng định như vậy.",
    ],
  },
  {
    id: "reading-memory",
    skill: "reading",
    title: "Why forgetting helps us learn",
    subtitle: "Hiểu lập luận trong bài học thuật",
    topic: "Giáo dục",
    level: "B2",
    minutes: 12,
    part: "Đọc hiểu • Bài ngắn",
    text: `A student who reads the same page five times may feel increasingly confident. The words look familiar, and the explanation seems obvious. But familiarity is not the same as the ability to recall information later. When the book is closed, that confident feeling can quickly disappear.\n\nRetrieval practice takes the opposite approach. Instead of repeatedly looking at an answer, learners try to produce it from memory. They might explain a concept without notes or answer a short quiz. This can feel harder than rereading, which sometimes leads students to believe that it is less effective. In fact, the effort of retrieval can strengthen later recall.\n\nSpacing adds another useful difficulty. Reviewing material across several days generally produces more durable learning than repeating it many times in one sitting. The ideal gap is not identical for every learner or every topic. If a question becomes too easy, the next review can be delayed. If the learner cannot retrieve the answer, an earlier review and a clear explanation may help.\n\nThese methods do not remove the need for understanding. Memorising an isolated definition is of limited value if a student cannot apply it. Useful practice therefore includes examples, explanations and feedback. Errors should be corrected rather than rehearsed repeatedly.\n\nA successful learning session may not always feel smooth. Some hesitation can be a sign that the brain is doing useful work. However, difficulty by itself is not a goal: tasks must still be manageable, and learners need opportunities to recover. The aim is steady progress, not exhaustion.`,
    questions: [
      q(
        "rm1",
        "Why can rereading create false confidence?",
        [
          "Familiar text may be mistaken for recall ability",
          "It always causes exhaustion",
          "Students never understand what they read",
          "It prevents any learning",
        ],
        0,
        "Đoạn 1 phân biệt cảm giác quen thuộc với khả năng tự nhớ lại.",
        "Suy luận",
      ),
      q(
        "rm2",
        "Which is an example of retrieval practice?",
        [
          "Copying a paragraph five times",
          "Highlighting every sentence",
          "Explaining a concept without notes",
          "Listening while looking at the answer",
        ],
        2,
        "Tự giải thích không nhìn ghi chú yêu cầu truy xuất kiến thức.",
      ),
      q(
        "rm3",
        "According to the passage, review intervals should:",
        [
          "Always be exactly one week",
          "Depend on performance and the material",
          "Never change after the first session",
          "Become shorter whenever a question is easy",
        ],
        1,
        "Khoảng cách thay đổi theo người học, nội dung và mức độ nhớ.",
      ),
      q(
        "rm4",
        "What does “durable” mean in paragraph three?",
        ["Entertaining", "Immediate", "Expensive", "Long-lasting"],
        3,
        "Durable learning là kiến thức được giữ lại lâu dài.",
        "Từ vựng trong ngữ cảnh",
      ),
      q(
        "rm5",
        "What warning does the final paragraph give?",
        [
          "All difficult tasks are harmful",
          "Smooth sessions are always ineffective",
          "Difficulty should remain manageable",
          "Recovery prevents progress",
        ],
        2,
        "Độ khó phải vừa sức, có thời gian hồi phục; không học đến kiệt sức.",
        "Ý chính",
      ),
    ],
    tips: [
      "Khi gặp từ lạ, đọc câu trước và câu sau để suy nghĩa.",
      "Tách điều tác giả khẳng định khỏi cách diễn đạt quá mạnh trong đáp án.",
    ],
  },
  {
    id: "reading-garden",
    skill: "reading",
    title: "A garden between buildings",
    subtitle: "Theo dấu chi tiết và từ tham chiếu",
    topic: "Môi trường",
    level: "B1",
    minutes: 10,
    part: "Đọc hiểu • Bài ngắn",
    text: `An empty piece of land between two apartment buildings used to collect rubbish. Last spring, several residents suggested turning it into a shared garden. They asked the building manager for permission and agreed to keep a clear path for emergency access. The manager approved a six-month trial rather than a permanent arrangement.\n\nTwenty households joined the project. Each contributed a small amount to buy soil and tools, while a nearby restaurant donated used wooden boxes for planting. Because the site received strong afternoon sunlight, the group chose vegetables that could tolerate heat. A retired gardener helped them decide what to plant.\n\nThe biggest challenge was not growing the vegetables but sharing the work. At first, a few enthusiastic residents did most of the watering. Others wanted to help but did not know when they were needed. The group created a weekly schedule, with morning and evening shifts. This made responsibilities clearer and prevented the same plants from being watered twice.\n\nChildren began visiting the garden with their parents. They measured how quickly the plants grew and learned that damaged leaves did not always mean a plant was dying. Some residents who had rarely spoken to their neighbours started exchanging recipes beside the vegetable beds.\n\nAt the end of the trial, the manager agreed that the garden could remain. It produced only a modest amount of food, but residents considered the new friendships its most valuable result. They are now discussing a covered bench, provided it does not block the emergency path.`,
    questions: [
      q(
        "rg1",
        "What condition did the manager set?",
        [
          "Only children could enter",
          "An emergency path had to stay clear",
          "Residents had to sell the vegetables",
          "The garden had to close after one month",
        ],
        1,
        "Đoạn 1: cư dân phải giữ lối đi cho tình huống khẩn cấp.",
      ),
      q(
        "rg2",
        "What did the restaurant provide?",
        [
          "Vegetable seeds",
          "Free meals",
          "Wooden planting boxes",
          "Watering equipment",
        ],
        2,
        "Nhà hàng cho các thùng gỗ đã qua sử dụng.",
      ),
      q(
        "rg3",
        "What problem did the schedule solve?",
        [
          "A lack of sunlight",
          "Poor soil quality",
          "Expensive tools",
          "An uneven distribution of work",
        ],
        3,
        "Lịch chia ca làm rõ trách nhiệm, tránh vài người gánh hết việc.",
      ),
      q(
        "rg4",
        "“This” in paragraph three refers to:",
        [
          "Creating a weekly schedule",
          "Buying new plants",
          "Moving the garden",
          "Asking children to help",
        ],
        0,
        "“This” nối với hành động ngay trước: lập lịch hằng tuần.",
        "Từ tham chiếu",
      ),
      q(
        "rg5",
        "What did residents value most?",
        [
          "The income from selling food",
          "The relationships they formed",
          "The size of the garden",
          "The new restaurant",
        ],
        1,
        "Đoạn cuối nêu “new friendships” là kết quả quý nhất.",
      ),
    ],
    tips: [
      "Từ “this/they/it” thường tham chiếu về ý hoặc danh từ vừa xuất hiện.",
      "Chọn đáp án có bằng chứng cụ thể trong đoạn văn.",
    ],
  },
  {
    id: "listening-weekend",
    skill: "listening",
    title: "A weekend worth planning",
    subtitle: "Nghe bắt thời gian, địa điểm và thay đổi",
    topic: "Cuộc sống Sài Gòn",
    level: "B1",
    minutes: 8,
    part: "Thông báo • Luyện ngắn",
    text: `Hello everyone, this is a message for people joining our Saturday walking tour. We were originally going to meet outside the city museum at eight thirty, but the museum entrance is being repaired. Please meet at the bookshop opposite the main post office instead. The starting time is now nine o'clock, so you have an extra half hour. Bring a bottle of water and a hat. There is no need to print your ticket; just show the booking email on your phone. The walk lasts about two hours and ends at a small local market. Lunch is not included in the ticket price, but you are welcome to stay at the market and eat together afterwards. If heavy rain is forecast, we will send you a cancellation email by seven on Saturday morning. Otherwise, the tour will go ahead, even if there is light rain. We look forward to seeing you.`,
    questions: [
      q(
        "lw1",
        "Where should participants meet?",
        [
          "At the museum entrance",
          "Inside the local market",
          "At the bookshop opposite the post office",
          "At the railway station",
        ],
        2,
        "Điểm hẹn được đổi sang hiệu sách đối diện bưu điện, không còn ở bảo tàng.",
      ),
      q(
        "lw2",
        "What time does the tour start?",
        ["8:00", "8:30", "9:00", "9:30"],
        2,
        "Người nói sửa giờ cũ 8:30 thành 9:00.",
        "Nghe thông tin thay đổi",
      ),
      q(
        "lw3",
        "What should participants show?",
        [
          "A printed map",
          "Their booking email",
          "A student card",
          "A lunch voucher",
        ],
        1,
        "Không cần in vé, chỉ cần email đặt chỗ trên điện thoại.",
      ),
      q(
        "lw4",
        "When will the tour be cancelled?",
        [
          "Whenever there is light rain",
          "If the market closes early",
          "If fewer than ten people arrive",
          "If heavy rain is forecast",
        ],
        3,
        "Chỉ hủy nếu dự báo mưa lớn; mưa nhẹ vẫn đi.",
      ),
    ],
    tips: [
      "Nghe đến cuối trước khi chốt đáp án: giờ hoặc địa điểm thường được sửa lại.",
      "Ghi nhanh số và danh từ, không cần chép cả câu.",
    ],
  },
  {
    id: "listening-library",
    skill: "listening",
    title: "A new chapter at the library",
    subtitle: "Nghe hướng dẫn và yêu cầu",
    topic: "Giáo dục",
    level: "B1",
    minutes: 8,
    part: "Thông báo • Luyện ngắn",
    text: `Welcome to the community library. Before you look around, I would like to explain a few changes. From next Monday, we will close at eight in the evening on weekdays instead of six. Weekend opening hours will remain the same. You can borrow up to six books for three weeks. To renew them, use our website or speak to a member of staff. You cannot renew a book if another reader has reserved it. The study room on the second floor is now available to book in one-hour slots. Booking is free, but you need a library card. Food is not allowed in the study room, although drinks in closed bottles are fine. Finally, our monthly writing group meets this Wednesday at six thirty. You do not need to bring a finished story, just a notebook and a willingness to share ideas. There are twelve places, so please register at the front desk if you are interested.`,
    questions: [
      q(
        "ll1",
        "What will change next Monday?",
        [
          "Weekend opening times",
          "The weekday closing time",
          "The cost of borrowing books",
          "The location of the library",
        ],
        1,
        "Ngày thường đóng cửa lúc 20:00 thay vì 18:00; cuối tuần không đổi.",
      ),
      q(
        "ll2",
        "When is renewal NOT possible?",
        [
          "After one week",
          "When done online",
          "When another reader has reserved the book",
          "When the reader has six books",
        ],
        2,
        "Sách được người khác đặt trước không thể gia hạn.",
      ),
      q(
        "ll3",
        "What is required to book the study room?",
        [
          "A library card",
          "A finished story",
          "A cash deposit",
          "A group of twelve people",
        ],
        0,
        "Phòng học miễn phí, cần thẻ thư viện.",
      ),
      q(
        "ll4",
        "What should people bring to the writing group?",
        [
          "A published book",
          "A laptop and printer",
          "A complete story",
          "A notebook",
        ],
        3,
        "Chỉ cần sổ ghi chép và sẵn sàng chia sẻ ý tưởng.",
      ),
    ],
    tips: [
      "Đọc lựa chọn trước khi nghe.",
      "Chú ý “instead of”, “remain the same”, “cannot” để tránh bẫy.",
    ],
  },
  {
    id: "listening-repair",
    skill: "listening",
    title: "Repair, don’t replace",
    subtitle: "Theo dõi luận điểm và ví dụ",
    topic: "Môi trường",
    level: "B2",
    minutes: 10,
    part: "Bài nói • Luyện ngắn",
    text: `Today I want to talk about repair cafés. Despite the name, their main purpose is not to serve coffee. They are community events where volunteers help people fix broken household items. Visitors might bring a lamp, a shirt with a torn pocket, or a bicycle with a loose brake. Most events are free, although donations help pay for materials. The idea is not that volunteers do everything while visitors wait. Owners are encouraged to take part so that they understand the repair and can attempt similar work in future. This educational aspect is as important as reducing waste. Of course, there are limits. Volunteers should not attempt a repair that is beyond their training, especially when electrical safety is involved. Some objects cannot be fixed because spare parts are unavailable. Critics sometimes argue that repairing an inexpensive item is not worth the time. However, this view considers only its replacement price. It overlooks the resources used to make and transport a new product, as well as the value of practical skills and community connections. Repair cafés will not solve the entire waste problem, but they offer a concrete place to begin.`,
    questions: [
      q(
        "lr1",
        "What is the main purpose of repair cafés?",
        [
          "To sell new appliances",
          "To serve inexpensive meals",
          "To help people repair items",
          "To train professional electricians",
        ],
        2,
        "Mục đích chính là giúp sửa vật dụng, không phải bán cà phê.",
        "Ý chính",
      ),
      q(
        "lr2",
        "Why are owners encouraged to participate?",
        [
          "To learn skills for future repairs",
          "To earn money from visitors",
          "To avoid talking to volunteers",
          "To test new products",
        ],
        0,
        "Chủ đồ cùng làm để hiểu và có thể tự sửa trong tương lai.",
      ),
      q(
        "lr3",
        "What limitation does the speaker mention?",
        [
          "Every repair must take an hour",
          "Replacement parts may be unavailable",
          "Only bicycles are accepted",
          "Visitors must hold a certificate",
        ],
        1,
        "Một số đồ không sửa được do thiếu linh kiện.",
      ),
      q(
        "lr4",
        "What does the speaker think critics overlook?",
        [
          "The taste of the coffee",
          "The number of paid staff",
          "The cost of renting shops",
          "Environmental and social benefits",
        ],
        3,
        "Người nói nhắc tài nguyên, kỹ năng và kết nối cộng đồng.",
        "Quan điểm người nói",
      ),
    ],
    tips: [
      "Ví dụ minh hoạ hỗ trợ luận điểm; đừng nhầm ví dụ với ý chính.",
      "Chú ý đoạn sau “however” khi hỏi quan điểm người nói.",
    ],
  },
  {
    id: "listening-flexible",
    skill: "listening",
    title: "Finding your best working hours",
    subtitle: "Nghe so sánh và kết luận",
    topic: "Công việc",
    level: "B2",
    minutes: 10,
    part: "Bài nói • Luyện ngắn",
    text: `Our company tested flexible working hours for three months. Employees could begin any time between seven and ten, provided they attended core meetings from ten to three and completed their contracted hours. We expected the main advantage to be shorter journeys, but the staff survey showed something different. Most employees valued being able to organise family responsibilities. Some travelled outside rush hour, but others still chose their usual schedule. Productivity remained roughly unchanged, which surprised managers who had expected it to fall. The main difficulty involved communication. Early starters sometimes finished before late starters had answered important questions. Teams responded by keeping a shared list of decisions and recording a short update before leaving. These measures helped, although urgent issues still required careful coordination. The trial did not include the customer support team because customers needed help at fixed times. We are now considering a shift-swapping system for that team instead. The results suggest that flexibility can work, but there is no single arrangement suitable for every role. Clear expectations matter more than simply allowing everyone to choose their hours.`,
    questions: [
      q(
        "lf1",
        "When did everyone need to be available for core meetings?",
        ["Seven to ten", "Ten to three", "Three to six", "Nine to five"],
        1,
        "Khung họp chung là 10 giờ đến 15 giờ.",
      ),
      q(
        "lf2",
        "What benefit did most staff value most?",
        [
          "Higher salaries",
          "Fewer contracted hours",
          "Managing family responsibilities",
          "Avoiding all meetings",
        ],
        2,
        "Kết quả khảo sát khác dự kiến: nhân viên coi trọng sắp xếp việc gia đình.",
      ),
      q(
        "lf3",
        "How did teams improve communication?",
        [
          "By keeping shared decisions and updates",
          "By cancelling all meetings",
          "By requiring identical starting times",
          "By reducing the number of employees",
        ],
        0,
        "Các nhóm giữ danh sách quyết định chung và cập nhật trước khi về.",
      ),
      q(
        "lf4",
        "What is the speaker’s conclusion?",
        [
          "Flexible hours always reduce productivity",
          "Every role should follow the same system",
          "Support staff should stop answering calls",
          "Flexibility needs clear expectations and suitable arrangements",
        ],
        3,
        "Kết luận: linh hoạt cần kỳ vọng rõ và cách sắp xếp hợp từng vai trò.",
        "Ý chính",
      ),
    ],
    tips: [
      "Phân biệt dự đoán ban đầu với kết quả thật.",
      "Ghi theo cặp: vấn đề → cách giải quyết.",
    ],
  },
  {
    id: "writing-email",
    skill: "writing",
    title: "An invitation to your city",
    subtitle: "Viết email thân mật có đủ ý",
    topic: "Cuộc sống Sài Gòn",
    level: "B1",
    minutes: 20,
    part: "Task 1 • Email",
    minWords: 120,
    text: `You have received an email from your English-speaking friend Alex:\n\n“I’m coming to Ho Chi Minh City for a weekend next month. Where should I stay? What could we do together? Also, what should I bring for the weather?”\n\nWrite an email to Alex. Recommend a place or area to stay, suggest activities you could do together, and give advice about what to pack. Write at least 120 words. Do not include your real name or address.`,
    questions: [],
    tips: [
      "Trả lời đủ 3 ý trong đề trước khi chăm chút từ vựng.",
      "Giọng thân mật: Hi Alex, … / See you soon, …",
      "Dành 2 phút cuối kiểm tra thì, số ít/số nhiều và chính tả.",
    ],
    sample: `Hi Alex,\n\nIt’s lovely to hear that you’re coming to Ho Chi Minh City! I’m really looking forward to spending the weekend with you.\n\nI suggest staying near the city centre because it will be easy to reach the places we want to visit. A small hotel near the book street would be a convenient choice. You should check recent reviews before booking.\n\nOn Saturday morning, we could explore the book street and visit the central post office. Afterwards, I’d love to take you to my favourite café. If you’re interested in local food, we could try a few dishes at a nearby market in the evening.\n\nThe weather can be hot and rainy, so bring light clothes, comfortable shoes and a small umbrella. A reusable water bottle would also be useful.\n\nLet me know when your flight arrives so we can make a plan.\n\nSee you soon,\nSam`,
  },
  {
    id: "writing-request",
    skill: "writing",
    title: "A request that gets a reply",
    subtitle: "Viết email trang trọng, rõ mục đích",
    topic: "Giáo dục",
    level: "B1",
    minutes: 20,
    part: "Task 1 • Email",
    minWords: 120,
    text: `You would like to attend an English course at a language centre, but you have a part-time job. Write an email to the course coordinator. Explain why you want to join, ask about evening or weekend classes, and request information about fees and learning materials. Write at least 120 words. Do not include your real name or address.`,
    questions: [],
    tips: [
      "Nêu mục đích ở đoạn đầu: I am writing to enquire about …",
      "Dùng câu hỏi lịch sự: Could you please let me know …?",
      "Nhớ hỏi cả học phí và tài liệu, không chỉ lịch học.",
    ],
    sample: `Dear Course Coordinator,\n\nI am writing to enquire about the English courses at your centre. I would like to improve my speaking and writing skills because I plan to take an English proficiency examination later this year.\n\nI currently have a part-time job on weekday afternoons, so I would be grateful if you could tell me whether you offer evening or weekend classes. I would also like to know how many lessons students attend each week and how long the course lasts.\n\nCould you please send me information about the course fees? In particular, I would like to know whether textbooks and online practice materials are included in the price. If there is a placement test, please let me know how I can register for it.\n\nThank you for your time. I look forward to hearing from you.\n\nYours faithfully,\nSam`,
  },
  {
    id: "writing-essay",
    skill: "writing",
    title: "Learning beyond the classroom",
    subtitle: "Xây luận điểm, ví dụ và phản biện",
    topic: "Giáo dục",
    level: "B2",
    minutes: 40,
    part: "Task 2 • Essay",
    minWords: 250,
    text: `Some people believe that online learning can replace traditional classroom education. Others think that face-to-face lessons remain essential. Discuss both views and give your own opinion. Support your answer with reasons and relevant examples. Write at least 250 words.`,
    questions: [],
    tips: [
      "Mở bài → lợi ích online → lợi ích trực tiếp → quan điểm và kết luận.",
      "Mỗi đoạn thân bài: luận điểm + giải thích + ví dụ.",
      "Không học thuộc đoạn mở bài quá chung chung; trả lời đúng câu hỏi “replace”.",
    ],
    sample: `Online education has made learning accessible to people who cannot regularly attend a classroom. While some believe it can fully replace traditional lessons, others argue that direct interaction remains necessary. In my view, online learning is valuable, but a combination of both approaches is usually more effective.\n\nOn the one hand, studying online offers considerable flexibility. Learners can review recorded lessons at a convenient time and pause difficult explanations. This is particularly useful for people with jobs or family responsibilities. For example, an employee preparing for an English examination can practise after work without spending an hour travelling to a language centre. Online courses may also make specialised subjects available to students who live far from qualified teachers. In addition, digital materials can be updated without printing new textbooks, and learners can revisit examples whenever they need extra practice.\n\nOn the other hand, classroom education provides support that can be difficult to reproduce online. Teachers can notice confusion and adjust an explanation immediately. Students also develop communication skills through group activities and informal conversations. A science experiment, for instance, may require equipment and supervision that learners do not have at home. Furthermore, some students struggle to remain focused when studying alone, especially if they lack a quiet space or reliable internet access.\n\nI believe the choice should depend on the learner and the subject rather than on technology alone. Recorded explanations and online quizzes can support independent study, while classroom sessions can focus on discussion, practical work and individual feedback. This arrangement uses the strengths of each method.\n\nIn conclusion, online learning can remove important barriers, but it cannot meet every educational need. A thoughtful balance between digital resources and face-to-face teaching is likely to offer the greatest benefit.`,
  },
  {
    id: "speaking-social",
    skill: "speaking",
    title: "Let’s talk about your everyday",
    subtitle: "Trả lời tự nhiên, không học thuộc",
    topic: "Cuộc sống Sài Gòn",
    level: "B1",
    minutes: 6,
    part: "Part 1 • Social interaction",
    text: `Topic 1: Your neighbourhood\n• What do you like about the area where you live?\n• Is there anything you would like to change?\n• Would you prefer to live in a quieter place? Why?\n\nTopic 2: Free time\n• What do you usually do to relax?\n• Do you prefer spending free time alone or with friends?\n• Have your hobbies changed since you were a child?`,
    questions: [],
    tips: [
      "Trả lời trực tiếp → giải thích → ví dụ nhỏ.",
      "Không cần dùng từ quá khó; ưu tiên rõ ý và nói tiếp được.",
      "Nghe lại xem mình có bỏ phần “why” không.",
    ],
  },
  {
    id: "speaking-solution",
    skill: "speaking",
    title: "One day, three possibilities",
    subtitle: "Chọn giải pháp và bảo vệ lựa chọn",
    topic: "Du lịch",
    level: "B2",
    minutes: 7,
    part: "Part 2 • Solution discussion",
    text: `Your friend is visiting your city for just one day. You want to plan an activity together. There are three options:\n\n1. Visiting a museum\n2. Taking a food tour\n3. Going to a shopping centre\n\nChoose the best option and explain why. Explain why the other two options are less suitable. You may assume your friend enjoys trying new things and has a limited budget.`,
    questions: [],
    tips: [
      "Nêu lựa chọn ngay từ đầu.",
      "Đưa ra 2 lý do gắn với ngân sách và sở thích của người bạn.",
      "So sánh cả 2 phương án còn lại, không chỉ khen phương án mình chọn.",
    ],
  },
  {
    id: "speaking-topic",
    skill: "speaking",
    title: "Small habits, meaningful change",
    subtitle: "Phát triển chủ đề và ý mở rộng",
    topic: "Sức khoẻ",
    level: "B2",
    minutes: 8,
    part: "Part 3 • Topic development",
    text: `Topic: Regular physical activity improves people’s lives.\n\nDevelop the topic using these suggested ideas:\n• Physical health\n• Mental well-being\n• Social connections\n• Your own ideas\n\nFollow-up questions:\n1. Why do some people find it difficult to exercise regularly?\n2. Should employers help their staff become more active?\n3. How can cities make exercise more accessible?`,
    questions: [],
    tips: [
      "Giới thiệu ý chính rồi mở rộng từng nhánh bằng lý do và ví dụ.",
      "Dùng “For instance”, “Another benefit”, “As a result” đúng ngữ cảnh.",
      "Dành thời gian cho câu hỏi mở rộng, tránh chỉ đọc lại các gợi ý.",
    ],
  },
];
export const lessons: Lesson[] = lessonDefinitions.map((lesson) => ({
  ...lesson,
  version: 1,
}));
export type Vocabulary = {
  id: string;
  word: string;
  ipa: string;
  meaning: string;
  example: string;
  topic: string;
};
export const vocabulary: Vocabulary[] = [
  {
    id: "v1",
    word: "reliable",
    ipa: "/rɪˈlaɪəbl/",
    meaning: "đáng tin cậy",
    example: "A reliable bus service helps people arrive on time.",
    topic: "Giao thông",
  },
  {
    id: "v2",
    word: "affordable",
    ipa: "/əˈfɔːdəbl/",
    meaning: "có giá phải chăng",
    example: "Students need affordable places to live.",
    topic: "Cuộc sống Sài Gòn",
  },
  {
    id: "v3",
    word: "take into account",
    ipa: "/teɪk ˈɪntu əˈkaʊnt/",
    meaning: "cân nhắc, tính đến",
    example: "We should take the weather into account when planning the trip.",
    topic: "Du lịch",
  },
  {
    id: "v4",
    word: "contribute",
    ipa: "/kənˈtrɪbjuːt/",
    meaning: "đóng góp",
    example: "Small daily habits can contribute to better health.",
    topic: "Sức khoẻ",
  },
  {
    id: "v5",
    word: "flexible",
    ipa: "/ˈfleksəbl/",
    meaning: "linh hoạt",
    example: "Flexible working hours help me organise my day.",
    topic: "Công việc",
  },
  {
    id: "v6",
    word: "opportunity",
    ipa: "/ˌɒpəˈtjuːnəti/",
    meaning: "cơ hội",
    example: "The language exchange is an opportunity to meet new people.",
    topic: "Giáo dục",
  },
  {
    id: "v7",
    word: "sustainable",
    ipa: "/səˈsteɪnəbl/",
    meaning: "bền vững",
    example: "Cycling is a sustainable way to travel short distances.",
    topic: "Môi trường",
  },
  {
    id: "v8",
    word: "rather than",
    ipa: "/ˈrɑːðə ðæn/",
    meaning: "thay vì",
    example: "I prefer learning a little every day rather than cramming.",
    topic: "Giáo dục",
  },
  {
    id: "v9",
    word: "as a result",
    ipa: "/æz ə rɪˈzʌlt/",
    meaning: "kết quả là, vì vậy",
    example: "She practised regularly. As a result, she became more confident.",
    topic: "Giáo dục",
  },
  {
    id: "v10",
    word: "convenient",
    ipa: "/kənˈviːniənt/",
    meaning: "thuận tiện",
    example: "The café is in a convenient location near my office.",
    topic: "Cuộc sống Sài Gòn",
  },
  {
    id: "v11",
    word: "raise awareness",
    ipa: "/reɪz əˈweənəs/",
    meaning: "nâng cao nhận thức",
    example: "Community projects can raise awareness of food waste.",
    topic: "Môi trường",
  },
  {
    id: "v12",
    word: "maintain",
    ipa: "/meɪnˈteɪn/",
    meaning: "duy trì",
    example: "It is easier to maintain a habit when it fits your routine.",
    topic: "Sức khoẻ",
  },
  {
    id: "v13",
    word: "essential",
    ipa: "/ɪˈsenʃl/",
    meaning: "thiết yếu",
    example: "Clear communication is essential for teamwork.",
    topic: "Công việc",
  },
  {
    id: "v14",
    word: "in contrast",
    ipa: "/ɪn ˈkɒntrɑːst/",
    meaning: "trái lại, ngược lại",
    example: "The city is busy. In contrast, the village is quiet.",
    topic: "Du lịch",
  },
  {
    id: "v15",
    word: "benefit from",
    ipa: "/ˈbenɪfɪt frəm/",
    meaning: "hưởng lợi từ",
    example: "Learners benefit from specific feedback on their writing.",
    topic: "Giáo dục",
  },
  {
    id: "v16",
    word: "manageable",
    ipa: "/ˈmænɪdʒəbl/",
    meaning: "vừa sức, có thể xử lý được",
    example: "Break a large goal into manageable steps.",
    topic: "Sức khoẻ",
  },
  {
    id: "v17",
    word: "on the other hand",
    ipa: "/ɒn ði ˈʌðə hænd/",
    meaning: "mặt khác",
    example:
      "Online lessons are flexible. On the other hand, they require self-discipline.",
    topic: "Giáo dục",
  },
  {
    id: "v18",
    word: "responsibility",
    ipa: "/rɪˌspɒnsəˈbɪləti/",
    meaning: "trách nhiệm",
    example: "The residents shared responsibility for watering the garden.",
    topic: "Công việc",
  },
  {
    id: "v19",
    word: "significant",
    ipa: "/sɪɡˈnɪfɪkənt/",
    meaning: "đáng kể, quan trọng",
    example: "Regular practice made a significant difference.",
    topic: "Giáo dục",
  },
  {
    id: "v20",
    word: "keep in touch",
    ipa: "/kiːp ɪn tʌtʃ/",
    meaning: "giữ liên lạc",
    example: "We keep in touch even though we live in different cities.",
    topic: "Cuộc sống Sài Gòn",
  },
];
export const sources = [
  {
    title: "VSTEP Test format · Trường ĐH Ngoại ngữ, ĐHQGHN",
    url: "https://vstep.vnu.edu.vn/test-format/",
  },
  {
    title: "Định dạng VSTEP bậc 3–5 · ĐH Sư phạm TP.HCM",
    url: "https://vstep.hcmue.edu.vn/index.php/gioi-thieu/dinh-dang-de-thi/bac-345",
  },
  {
    title: "Lịch thi & đăng ký · ĐH Sư phạm TP.HCM",
    url: "https://vstep.hcmue.edu.vn/index.php/lich-thi",
  },
  {
    title: "Thông tin kỳ thi · ĐH KHXH&NV, ĐHQG-HCM",
    url: "https://thitienganh6bac.hcmussh.edu.vn/",
  },
];
