import { lessons, type Lesson, type Question } from "./content";
const question = (
  id: string,
  text: string,
  options: string[],
  answer: number,
  explanation: string,
  tag = "Thông tin chi tiết",
): Question => ({ id, text, options, answer, explanation, tag });
const extendReading = (
  id: string,
  extra: string,
  questions: Question[],
): Lesson => {
  const base = lessons.find((l) => l.id === id)!;
  return {
    ...base,
    id: `full-${id}`,
    minutes: 15,
    part: "Đề đầy đủ · Reading",
    text: `${base.text}\n\n${extra}`,
    questions: [
      ...base.questions.map((q) => ({ ...q, id: `full-${q.id}` })),
      ...questions,
    ],
  };
};
export const fullReading: Lesson[] = [
  extendReading(
    "reading-cafe",
    `To understand how well the study room was working, Linh asked visitors to complete a short anonymous questionnaire. She deliberately avoided collecting names or contact details. Most respondents praised the quiet atmosphere, but several mentioned that the booking page was difficult to use on a phone. Linh simplified it so that a customer needed only to select a date and a time. She also kept two seats available for people who arrived without a reservation.\n\nAnother suggestion concerned the length of bookings. A two-hour limit initially seemed fair, yet students preparing for examinations often needed longer. Linh introduced a simple compromise: visitors could extend their booking if nobody else was waiting. This prevented empty seats from remaining unused while still giving newcomers a reasonable chance to find a place. Staff explained the policy on a small sign rather than reminding each customer separately.\n\nThe café also changed how it handled waste. Reusable cups became standard for customers staying inside, and a discount encouraged takeaway customers to bring their own containers. Linh admitted that washing cups required additional staff time. Nevertheless, she considered the reduction in disposable packaging worthwhile. She did not describe the café as completely sustainable, because ingredients still arrived in plastic and electricity use remained significant.\n\nLooking back, Linh says that none of these changes was revolutionary. Their value came from responding to ordinary problems consistently. She plans to repeat the questionnaire every few months, accepting that the needs of her customers will continue to change.`,
    [
      question(
        "frc6",
        "Why did Linh make the questionnaire anonymous?",
        [
          "To collect customers’ phone numbers",
          "To receive feedback without collecting identities",
          "To advertise a new website",
          "To identify the most frequent visitors",
        ],
        1,
        "Phiếu hỏi không thu tên hoặc liên hệ; phản hồi được lấy mà không gắn danh tính.",
      ),
      question(
        "frc7",
        "What change was made to the booking system?",
        [
          "Customers had to pay in advance",
          "All bookings had to be made by phone",
          "The mobile process was simplified",
          "Seats were no longer available online",
        ],
        2,
        "Đoạn bổ sung nói trang khó dùng trên điện thoại, nên Linh rút gọn thao tác.",
      ),
      question(
        "frc8",
        "When could a visitor extend a booking?",
        [
          "When no one else was waiting",
          "Only after buying three drinks",
          "Only on Thursday evenings",
          "When all other seats were occupied",
        ],
        0,
        "Có thể gia hạn nếu không có người đang chờ.",
      ),
      question(
        "frc9",
        "What trade-off did Linh acknowledge about reusable cups?",
        [
          "They made drinks more expensive to prepare",
          "They prevented customers from staying inside",
          "They increased advertising costs",
          "They required extra time for washing",
        ],
        3,
        "Linh thừa nhận việc rửa cốc cần thêm thời gian của nhân viên.",
      ),
      question(
        "frc10",
        "Which description best fits Linh’s approach?",
        [
          "A fixed plan that never changes",
          "Small adjustments informed by ongoing feedback",
          "An attempt to attract only students",
          "Rapid expansion into several new locations",
        ],
        1,
        "Tổng thể bài nhấn mạnh thay đổi nhỏ, đều đặn dựa trên phản hồi.",
        "Quan điểm tác giả",
      ),
    ],
  ),
  extendReading(
    "reading-commute",
    `The practical details of a transport policy can determine whether it achieves its aims. Consider a city that introduces an excellent bus route but provides no safe pavement leading to its stops. Parents with small children and people with limited mobility may still find the service difficult to use. A journey begins at the front door, not at the point where a passenger boards a vehicle. Planners therefore need to examine the whole trip, including the first and last few hundred metres.\n\nInformation is another relatively small investment with potentially wide benefits. Clear maps, readable signs and accurate arrival estimates reduce the uncertainty associated with an unfamiliar service. Visitors may need explanations that regular passengers no longer notice are missing. Consulting only existing users can consequently produce an incomplete picture of the barriers that keep others away.\n\nBusinesses also have a role. A shop owner may initially oppose removing a few parking spaces to create a safer crossing. However, the effect should be investigated rather than assumed. In some neighbourhoods, many customers already arrive on foot. Making their journeys easier may be more valuable than preserving every parking place. In other locations, deliveries or limited alternatives require a different arrangement.\n\nGood evaluation should record who benefits and who remains excluded. An average journey time can improve even while a particular group faces longer waits. Comparing experiences across different neighbourhoods and working schedules helps reveal these differences. Public discussion becomes more useful when it considers this evidence rather than treating every commuter as if they had identical needs.`,
    [
      question(
        "frt6",
        "Why does the author discuss the pavement near bus stops?",
        [
          "To argue that bus stops should be removed",
          "To show that the entire journey needs consideration",
          "To recommend banning parents from buses",
          "To claim that buses are always inaccessible",
        ],
        1,
        "Chuyến đi tính từ cửa nhà; thiếu vỉa hè an toàn làm tuyến xe tốt vẫn khó tiếp cận.",
        "Mục đích tác giả",
      ),
      question(
        "frt7",
        "What can clear maps and arrival estimates reduce?",
        [
          "Uncertainty about using a service",
          "The physical length of every journey",
          "The need for any transport staff",
          "The number of buses in operation",
        ],
        0,
        "Thông tin rõ giúp hành khách bớt bất định khi dùng tuyến chưa quen.",
      ),
      question(
        "frt8",
        "Why might a survey of current passengers be incomplete?",
        [
          "Current passengers never answer honestly",
          "It includes too many shop owners",
          "It misses barriers experienced by non-users",
          "It cannot measure fares",
        ],
        2,
        "Người đang dùng xe đã quen dịch vụ; người chưa dùng có thể gặp rào cản khác.",
        "Suy luận",
      ),
      question(
        "frt9",
        "What does the author recommend before changing parking provision?",
        [
          "Assuming that all customers drive",
          "Removing every parking space immediately",
          "Ignoring delivery requirements",
          "Investigating local travel patterns",
        ],
        3,
        "Tác giả khuyên khảo sát thực tế khách đi bằng gì và nhu cầu giao hàng.",
      ),
      question(
        "frt10",
        "Why can average journey times be misleading?",
        [
          "They are never based on real journeys",
          "They can conceal disadvantages for particular groups",
          "They measure only the price of travel",
          "They always increase when buses improve",
        ],
        1,
        "Giá trị trung bình tốt hơn vẫn có thể che việc một nhóm phải chờ lâu hơn.",
        "Suy luận",
      ),
    ],
  ),
  extendReading(
    "reading-memory",
    `One teacher applied these ideas by beginning each lesson with three questions from earlier topics. The questions were not graded, and students answered individually before discussing their reasoning in pairs. At first, several students felt uncomfortable when they could not remember an answer. The teacher explained that these moments were useful signals about what needed attention, rather than evidence that a student lacked ability.\n\nFeedback was deliberately specific. Instead of writing only that an answer was wrong, the teacher identified the misunderstanding and gave a contrasting example. A learner who confused two similar words, for instance, saw each word in a different sentence. Students then wrote a sentence of their own to demonstrate that they understood the distinction. Simply copying the correction was not considered sufficient.\n\nThe teacher also asked students to predict which answers they would remember a week later. Comparing those predictions with actual performance helped some learners recognise that an easy-feeling study session could produce weak recall. Others discovered that they had underestimated themselves. The purpose was to improve decisions about future practice, not to rank students against one another.\n\nTechnology can make this process convenient by keeping a record of previous responses and suggesting review dates. Nevertheless, an application cannot directly observe understanding from a single button press. Learners need to judge their own recall honestly and occasionally test their knowledge in a new situation. A scheduling system is most useful when it supports thoughtful practice rather than replacing it with a series of mechanical clicks.`,
    [
      question(
        "frm6",
        "How were the teacher’s opening questions used?",
        [
          "As a graded examination",
          "As an ungraded review of earlier topics",
          "As a competition between classes",
          "As an introduction to unrelated subjects",
        ],
        1,
        "Ba câu hỏi đầu giờ ôn nội dung cũ và không tính điểm.",
      ),
      question(
        "frm7",
        "What did the teacher provide when a learner confused two words?",
        [
          "A longer list to copy",
          "No feedback until the final exam",
          "Contrasting examples in sentences",
          "A lower score for participation",
        ],
        2,
        "Giáo viên cho hai từ trong hai câu tương phản để làm rõ sự khác nhau.",
      ),
      question(
        "frm8",
        "What did students do after receiving the contrasting examples?",
        [
          "Write their own sentence",
          "Memorise the teacher’s grade",
          "Avoid using the words again",
          "Copy the same correction repeatedly",
        ],
        0,
        "Sau đó học sinh viết câu của riêng mình để thể hiện đã hiểu.",
      ),
      question(
        "frm9",
        "What was the purpose of predicting future recall?",
        [
          "To divide students into permanent ability groups",
          "To make every task easier",
          "To replace future practice with predictions",
          "To improve choices about later study",
        ],
        3,
        "So sánh dự đoán với thực tế nhằm giúp quyết định cách học tiếp.",
        "Mục đích tác giả",
      ),
      question(
        "frm10",
        "What limitation of learning applications is mentioned?",
        [
          "They cannot store previous responses",
          "A button press does not directly prove understanding",
          "They always set identical review dates",
          "They prevent learning in new situations",
        ],
        1,
        "Một lần bấm nút không trực tiếp chứng minh hiểu bài; vẫn cần tự nhớ và vận dụng.",
        "Suy luận",
      ),
    ],
  ),
  extendReading(
    "reading-garden",
    `The residents kept a simple notebook beside the entrance to record tasks and observations. It included watering dates, signs of insects and the amount harvested each week. The notebook was intended to help newcomers participate without depending on the retired gardener for every decision. Several entries were accompanied by drawings so that younger children could understand them too.\n\nAs the rainy season approached, drainage became a concern. Water sometimes collected underneath the planting boxes, attracting mosquitoes. The group raised the boxes on supports and checked that containers did not retain standing water. They also reviewed which plants were suitable for the changing weather. Some vegetables were replaced, while others were moved to positions with better shelter.\n\nThere were occasional disagreements about how to divide the harvest. One resident proposed giving most of the vegetables to those who had worked the longest hours. Others argued that older people and busy parents might contribute in less visible ways, such as sharing knowledge or lending tools. The group eventually agreed to distribute small portions among participating households and offer any surplus to neighbours who wanted to try the produce.\n\nThe project remained informal, but decisions were written down after monthly meetings. Residents found that clear agreements reduced misunderstandings without making the garden feel like another workplace. They were careful not to promise that it would feed the entire building. For them, its greatest contribution was a shared reason to step outside, notice the seasons and take an interest in people living nearby.`,
    [
      question(
        "frg6",
        "What was the main purpose of the garden notebook?",
        [
          "To calculate a profit from selling food",
          "To help people participate and make decisions",
          "To replace all monthly meetings",
          "To record private information about neighbours",
        ],
        1,
        "Sổ ghi việc và quan sát giúp người mới tham gia mà không lệ thuộc một người.",
      ),
      question(
        "frg7",
        "Why were some entries illustrated?",
        [
          "To advertise the restaurant",
          "To identify paying customers",
          "To make them understandable to younger children",
          "To hide information from new residents",
        ],
        2,
        "Hình vẽ giúp trẻ nhỏ cũng hiểu các ghi chép.",
      ),
      question(
        "frg8",
        "What caused concern as the rainy season approached?",
        [
          "Water gathering beneath the boxes",
          "Too many vegetables being harvested",
          "A lack of available volunteers",
          "The restaurant closing permanently",
        ],
        0,
        "Nước đọng dưới thùng có thể thu hút muỗi, nên cư dân nâng thùng và kiểm tra thoát nước.",
      ),
      question(
        "frg9",
        "How did the group finally agree to share the harvest?",
        [
          "Sell it all to the restaurant",
          "Give everything to the longest-serving volunteer",
          "Keep it only for the children",
          "Distribute portions among participants and share the surplus",
        ],
        3,
        "Chia phần nhỏ cho hộ tham gia; dư thì mời hàng xóm thử.",
      ),
      question(
        "frg10",
        "What does the final paragraph suggest about clear agreements?",
        [
          "They necessarily create an unpleasant workplace",
          "They can prevent misunderstandings while preserving an informal atmosphere",
          "They remove the need for cooperation",
          "They guarantee enough food for every resident",
        ],
        1,
        "Thỏa thuận rõ giúp tránh hiểu lầm mà không biến khu vườn thành nơi làm việc nặng nề.",
        "Suy luận",
      ),
    ],
  ),
];
const listen = (
  id: string,
  title: string,
  part: string,
  text: string,
  questions: Question[],
  minutes: number,
): Lesson => ({
  id,
  skill: "listening",
  title,
  subtitle: "Đề tự biên soạn đủ cấu trúc · Giọng đọc tổng hợp",
  topic: "Luyện đề",
  level: "B2",
  minutes,
  part,
  text,
  questions,
  tips: [],
});
export const fullListening: Lesson[] = [
  listen(
    "full-listen-1",
    "A change at the station",
    "Part 1 · Thông báo 1",
    `Attention passengers travelling to Riverside. The ten fifteen service will leave from platform four today, not platform two as shown on some printed tickets. There is no change to the departure time. Please use the stairs or lift at the end of the main hall to reach platform four. Staff in blue jackets can help passengers who need assistance. We apologise for the inconvenience caused by maintenance work on the usual platform.`,
    [
      question(
        "fl1",
        "What has changed about the Riverside service?",
        [
          "Its departure time",
          "Its destination",
          "Its departure platform",
          "Its ticket price",
        ],
        2,
        "Giờ và điểm đến không đổi; sân ga đổi từ 2 sang 4.",
      ),
    ],
    1,
  ),
  listen(
    "full-listen-2",
    "At the sports centre",
    "Part 1 · Thông báo 2",
    `This is a reminder for members of the sports centre. The swimming pool will be closed on Wednesday while the filters are replaced. The gym and indoor courts will remain open as usual. Members with a swimming lesson on Wednesday can attend an extra session on Friday at no additional cost. Please contact reception before Tuesday evening if you would like to take this option. The pool is expected to reopen on Thursday morning.`,
    [
      question(
        "fl2",
        "What is offered to members whose Wednesday swimming lesson is cancelled?",
        [
          "A free extra session on Friday",
          "A permanent reduction in membership fees",
          "A lesson in the gym",
          "A refund for the entire month",
        ],
        0,
        "Thông báo cho phép học bù thứ Sáu không tính thêm phí.",
      ),
    ],
    1,
  ),
  listen(
    "full-listen-3",
    "A delivery message",
    "Part 1 · Tin nhắn 3",
    `Hello, this is Green Basket calling about your grocery delivery. Our driver tried to reach your building this morning but could not enter because the access code was missing from the order. We still have your items and can deliver them this afternoon between three and five. Please call us back with the correct code. You do not need to place another order or pay another delivery charge. Thank you.`,
    [
      question(
        "fl3",
        "What does the customer need to do?",
        [
          "Pay a second delivery fee",
          "Collect the groceries from the shop",
          "Place a new order online",
          "Provide the building access code",
        ],
        3,
        "Cần gọi lại cung cấp mã ra vào; không đặt lại hay trả thêm phí.",
      ),
    ],
    1,
  ),
  listen(
    "full-listen-4",
    "A workshop reminder",
    "Part 1 · Thông báo 4",
    `Thank you for registering for Saturday's photography workshop. Please bring a fully charged camera or a smartphone. Expensive equipment is not necessary because we will concentrate on light and composition. The first hour takes place inside the community centre, followed by a short walk around the neighbourhood. If it rains, we will practise beside the large windows indoors instead. The workshop begins at two, and tea will be available from one forty-five.`,
    [
      question(
        "fl4",
        "What will the workshop mainly focus on?",
        [
          "Buying professional cameras",
          "Light and composition",
          "Editing videos for social media",
          "Printing large photographs",
        ],
        1,
        "Nội dung tập trung vào ánh sáng và bố cục, không yêu cầu thiết bị đắt tiền.",
      ),
    ],
    1,
  ),
  listen(
    "full-listen-5",
    "A message from a colleague",
    "Part 1 · Tin nhắn 5",
    `Hi, it is Daniel. I have finished checking the figures for tomorrow's presentation. Everything looks correct except the chart on slide seven, which still shows last month's totals. Could you replace it with the chart I emailed this morning? Please keep the introduction as it is because the manager has already approved it. I will be away from my desk until four, but you can message me if anything is unclear.`,
    [
      question(
        "fl5",
        "What does Daniel ask his colleague to change?",
        [
          "The introduction",
          "The presentation date",
          "The chart on slide seven",
          "All of the figures",
        ],
        2,
        "Chỉ biểu đồ ở slide 7 còn số tháng trước; phần mở đầu giữ nguyên.",
      ),
    ],
    1,
  ),
  listen(
    "full-listen-6",
    "A neighbourhood event",
    "Part 1 · Thông báo 6",
    `Our neighbourhood book exchange takes place this Sunday in the courtyard. You may bring up to five books in good condition and choose the same number to take home. Please avoid bringing textbooks with answers written on every page, as they are difficult for other readers to use. Children are welcome, and there will be a separate table for picture books. Any books left at the end will be donated to a community reading room.`,
    [
      question(
        "fl6",
        "What will happen to books remaining after the event?",
        [
          "They will be donated",
          "They will be sold online",
          "They will be returned by post",
          "They will be thrown away",
        ],
        0,
        "Sách còn lại được tặng cho phòng đọc cộng đồng.",
      ),
    ],
    1,
  ),
  listen(
    "full-listen-7",
    "At the clinic",
    "Part 1 · Tin nhắn 7",
    `Good afternoon. This is a message from Park Clinic about your appointment next Monday. The doctor will be attending training in the morning, so we need to move your appointment from nine to two thirty in the afternoon. The appointment will still be with the same doctor in the same room. If the new time is inconvenient, please call reception to arrange a different day. There is no need to complete the registration form again.`,
    [
      question(
        "fl7",
        "What is the new appointment time?",
        [
          "9:00 on Monday",
          "2:30 on Tuesday",
          "9:00 on Tuesday",
          "2:30 on Monday",
        ],
        3,
        "Cuộc hẹn dời từ 9 giờ sang 14:30 cùng thứ Hai.",
      ),
    ],
    1,
  ),
  listen(
    "full-listen-8",
    "Museum entry",
    "Part 1 · Thông báo 8",
    `Visitors arriving for the evening exhibition should use the entrance on Garden Street. The main entrance closes at five, but the Garden Street entrance remains open until eight thirty. Your exhibition ticket includes access to the permanent galleries, although the rooftop terrace is closed this evening because of strong winds. Please leave large bags in the lockers near reception. Small handbags and cameras may be taken into the galleries.`,
    [
      question(
        "fl8",
        "Which area is unavailable this evening?",
        [
          "The permanent galleries",
          "The rooftop terrace",
          "The Garden Street entrance",
          "The reception lockers",
        ],
        1,
        "Sân thượng đóng vì gió mạnh; phòng trưng bày vẫn mở.",
      ),
    ],
    1,
  ),
  listen(
    "full-listen-9",
    "Choosing an evening course",
    "Part 2 · Hội thoại 1",
    `Adviser: Good afternoon. How can I help you?\nLearner: I am interested in an evening English course, but I am not sure which one would suit me. I work in a small hotel, and I need to communicate more confidently with guests.\nAdviser: Have you studied at our centre before?\nLearner: No. I did an online course last year, mostly grammar exercises. I could finish those quite easily, but when someone asked me a question unexpectedly, I struggled to answer.\nAdviser: In that case, our communication course might be useful. It includes role plays, listening activities and some short writing tasks. We offer a Monday and Wednesday group and a Tuesday and Thursday group.\nLearner: I usually work late on Wednesdays, so the second group sounds better. What time does it start?\nAdviser: At six thirty, finishing at eight. The course lasts eight weeks. Before you enrol, we ask you to complete a short placement task so that we can suggest a suitable group.\nLearner: Is that an official proficiency examination?\nAdviser: No, it is only for our course planning. It does not provide a certificate of language level. You answer some questions online and have a brief conversation with a teacher.\nLearner: That is fine. I am a little worried about being in a large class. My online group had almost forty people, and there was very little time to speak.\nAdviser: We limit these groups to twelve. Pair work is a regular part of the lesson, so students do not have to wait for a whole-class discussion to practise.\nLearner: And what happens if I miss a lesson because of a change in my work schedule?\nAdviser: We can send you the handouts and a summary of the activities. We do not record every lesson, because students may not feel comfortable being recorded. You can also ask the teacher a question before the following class.\nLearner: I appreciate that. Does the fee include a textbook?\nAdviser: The fee includes all materials used in class. There is an optional workbook for extra practice, but you do not have to buy it.\nLearner: Then I would like to take the placement task first. I can come on Saturday morning.\nAdviser: That should be possible. I will check the teacher's appointments and email you a time this afternoon. Please wait for that confirmation before making travel plans.`,
    [
      question(
        "fl9",
        "What does the learner most want to improve?",
        [
          "Completing grammar exercises quickly",
          "Communicating confidently with hotel guests",
          "Writing academic research papers",
          "Translating technical documents",
        ],
        1,
        "Người học làm ở khách sạn và muốn giao tiếp tự tin với khách.",
      ),
      question(
        "fl10",
        "Why does the learner prefer the Tuesday and Thursday group?",
        [
          "It has a lower fee",
          "It is an online-only course",
          "It avoids a regular late shift on Wednesday",
          "It begins later than the other group",
        ],
        2,
        "Thứ Tư thường làm muộn nên nhóm thứ Ba/Năm phù hợp hơn.",
      ),
      question(
        "fl11",
        "What does the adviser say about missed lessons?",
        [
          "The centre provides materials and an activity summary",
          "Every lesson is recorded automatically",
          "Students must pay for another course",
          "No support is available",
        ],
        0,
        "Trung tâm gửi handout và tóm tắt hoạt động; không ghi hình mọi buổi.",
      ),
      question(
        "fl12",
        "What should the learner do before travelling on Saturday?",
        [
          "Buy the optional workbook",
          "Complete an official examination",
          "Pay for a hotel room",
          "Wait for an appointment confirmation",
        ],
        3,
        "Cố vấn sẽ kiểm tra lịch và email giờ hẹn, cần chờ xác nhận.",
      ),
    ],
    4,
  ),
  listen(
    "full-listen-10",
    "Planning a community project",
    "Part 2 · Hội thoại 2",
    `Mai: Have you looked at the proposals for our community project? We need to choose one before Friday.\nBen: Yes. The river clean-up would be useful, but I am concerned about safety. Some sections have steep banks, and we would need someone experienced to supervise us.\nMai: I spoke to the local environmental group. They can provide a supervisor next month, but not on the weekend our volunteers are available.\nBen: Then perhaps we should consider the second proposal, helping the reading room organise its donated books.\nMai: That is my preference too. The room has received several hundred books, but visitors struggle to find what they want. The coordinator asked us to sort them into broad categories and label the shelves.\nBen: Would we need to enter every book into a computer database? That could take much longer than one weekend.\nMai: Not at this stage. The coordinator wants a simple arrangement that the regular volunteers can maintain. A complicated system would create more work for them later.\nBen: Good point. How many people can work in the room comfortably?\nMai: About eight at a time. We have sixteen volunteers, so I suggest two shifts. One group could work in the morning and the other after lunch.\nBen: That would leave enough space to move the boxes. We should ask people which shift they prefer rather than assigning everyone immediately.\nMai: Agreed. We also need some labels and markers. I thought we could use part of our budget, but a nearby stationery shop has offered to donate them.\nBen: That is helpful. We should still keep a small amount for unexpected costs. What about books that are damaged or unsuitable?\nMai: The coordinator will make those decisions. We should put questionable items aside instead of throwing anything away ourselves. Some old books may be useful even if their covers are worn.\nBen: Shall I prepare a short instruction sheet explaining the categories?\nMai: Yes, please. I will confirm the dates with the coordinator and ask whether the room can remain closed to visitors during the work. It would be difficult to sort books while people are borrowing them.\nBen: Once we have that confirmation, I can send the shift survey to the volunteers.\nMai: Perfect. Let us also take a few photographs of the finished shelves, with the coordinator's permission, so everyone can see what their work achieved.`,
    [
      question(
        "fl13",
        "Why is the river clean-up not selected?",
        [
          "The river has already been cleaned",
          "No volunteers are interested",
          "The available supervisor cannot attend the chosen weekend",
          "The project would require no teamwork",
        ],
        2,
        "Giám sát có chuyên môn không rảnh đúng cuối tuần tình nguyện viên có thể tham gia.",
      ),
      question(
        "fl14",
        "What kind of book organisation does the coordinator want?",
        [
          "A simple system with broad categories",
          "A detailed database completed before opening",
          "A separate room for every author",
          "A system maintained only by paid staff",
        ],
        0,
        "Điều phối viên muốn phân loại rộng và nhãn kệ dễ duy trì.",
      ),
      question(
        "fl15",
        "Why are two shifts proposed?",
        [
          "To avoid providing any instructions",
          "To keep the number working at once manageable",
          "To increase the registration fee",
          "To allow visitors to borrow more books",
        ],
        1,
        "Phòng chỉ đủ khoảng tám người, trong khi có mười sáu tình nguyện viên.",
      ),
      question(
        "fl16",
        "Who will decide what to do with questionable books?",
        [
          "The stationery shop owner",
          "Any volunteer who finds them",
          "The photographer",
          "The reading-room coordinator",
        ],
        3,
        "Sách đáng ngờ để riêng cho điều phối viên quyết định; không tự bỏ.",
      ),
    ],
    4,
  ),
  listen(
    "full-listen-11",
    "Reviewing a workplace trial",
    "Part 2 · Hội thoại 3",
    `Manager: Thanks for collecting the feedback on our new meeting schedule, Rosa. What did people think?\nRosa: Most staff liked having fewer meetings. They said it was easier to finish tasks that required concentration. But the comments were not entirely positive.\nManager: I expected the sales team to be unhappy because they used the Monday meeting to share customer news.\nRosa: Surprisingly, they adapted quite well. They now write a short update in the shared document. The biggest concern came from new employees, who had used the regular meetings to learn who was responsible for different tasks.\nManager: That makes sense. Experienced staff already know whom to contact. Did anyone suggest a solution?\nRosa: Several people proposed a short weekly question session for newer staff. It would be optional for everyone else, and the person leading it could change each week.\nManager: I like that better than bringing back every meeting. What about the project teams?\nRosa: They appreciated the rule that each meeting should have a clear purpose and a written decision afterwards. However, some said that a strict twenty-minute limit was unrealistic when a complex decision had to be discussed.\nManager: Perhaps the limit should be a default rather than an absolute rule. A team could request more time if it explains why.\nRosa: That was one of the suggestions. People also asked us not to interpret a shorter calendar as proof that all communication had improved. A few discussions simply moved into private messages, where other team members could not see them.\nManager: So we need to consider where decisions are recorded, not only how much time people spend in a meeting.\nRosa: Exactly. I would recommend keeping the shared decision notes and reviewing them after another month. We should also ask people who work remotely whether they receive the same information as those in the office.\nManager: Can we compare the number of completed projects before and after the trial?\nRosa: We can, but that number alone would be misleading. Some recent projects were much smaller, and two teams had extra staff. We should include those differences in the report.\nManager: All right. Please prepare a summary with the benefits, the concerns and those qualifications. We will discuss the optional question session next week.\nRosa: I will. I will also include a recommendation to check the system again after the next group of employees joins.`,
    [
      question(
        "fl17",
        "Which group reported the biggest concern?",
        [
          "The sales team",
          "New employees",
          "All remote customers",
          "The accounting team",
        ],
        1,
        "Nhân viên mới thiếu cơ hội tìm hiểu ai phụ trách việc gì.",
      ),
      question(
        "fl18",
        "What is suggested for newer staff?",
        [
          "A compulsory daily presentation",
          "Returning to every previous meeting",
          "An optional weekly question session",
          "Working only from the office",
        ],
        2,
        "Đề xuất buổi hỏi đáp hằng tuần; người khác tham gia tự nguyện.",
      ),
      question(
        "fl19",
        "How does the manager respond to the twenty-minute limit?",
        [
          "It should allow justified exceptions",
          "It must never be changed",
          "Every meeting should be cancelled",
          "It should apply only to customer calls",
        ],
        0,
        "Giới hạn nên là mặc định, có thể thêm giờ khi giải thích được lý do.",
      ),
      question(
        "fl20",
        "Why is the number of completed projects insufficient evidence?",
        [
          "No projects were completed",
          "Employees refused to report their work",
          "The report cannot include numbers",
          "Project size and staffing also changed",
        ],
        3,
        "Quy mô dự án và số nhân viên thay đổi nên không thể chỉ nhìn số dự án.",
        "Suy luận",
      ),
    ],
    4,
  ),
  listen(
    "full-listen-12",
    "What makes a neighbourhood walkable?",
    "Part 3 · Bài nói 1",
    `When people hear the word walkability, they often think about distance. If a grocery shop is only ten minutes away, they assume that walking to it must be convenient. Yet distance is only one part of the experience. A short route with dangerous crossings, broken pavements or no shade may discourage walking more than a slightly longer but comfortable route. Today I will discuss three features that help explain this difference.\n\nThe first is continuity. Imagine walking along a good pavement that suddenly ends at a busy junction. The quality of the earlier section does not remove the difficulty of crossing the final road. People with pushchairs, walking aids or heavy shopping may face an even greater obstacle. A useful walking network therefore needs connected routes rather than a collection of attractive but isolated pieces. When local authorities evaluate an improvement, they should follow a complete journey from a home to an everyday destination.\n\nThe second feature is comfort. Shade, places to rest and protection from fast-moving traffic influence whether people feel able to walk. These features are sometimes described as decorative extras, but that description overlooks their practical importance. An older resident may be willing to walk to a park if there is a bench halfway along the route. Without somewhere to rest, the same journey may be unrealistic. Similarly, a parent may avoid a route where a child must walk immediately beside speeding vehicles.\n\nThe third feature is usefulness. A beautiful path is less likely to become part of daily life if it leads nowhere people need to go. Routes connecting homes with schools, shops, public transport and community facilities offer more reasons to walk. This does not mean that every street must contain every type of service. It means that planners should consider how destinations fit together across an area.\n\nMeasuring the results also requires care. Counting pedestrians at one location can show that a particular street is busy, but it cannot explain who still avoids it. A survey might reveal that residents who walk confidently are satisfied while people with limited mobility continue to face difficulties. Their experiences should not disappear inside an average satisfaction score.\n\nResidents can contribute valuable knowledge. They know where rainwater collects, which crossing feels unsafe after dark and where a delivery vehicle regularly blocks the pavement. Short guided walks with different groups can reveal problems that are easy to miss on a map. These conversations do not replace technical assessment, but they can make that assessment more relevant.\n\nFinally, improvements need maintenance. A new bench that is never repaired or a crossing whose markings fade may provide only a temporary benefit. Walkability is therefore not a one-time design achievement. It is an ongoing commitment to making ordinary journeys possible, comfortable and useful for a wider range of people.`,
    [
      question(
        "fl21",
        "What is the speaker’s main point about distance?",
        [
          "It is only one factor in walkability",
          "It is the only reliable measure",
          "Short routes are always comfortable",
          "Long routes should never be improved",
        ],
        0,
        "Khoảng cách chỉ là một yếu tố; an toàn, tiện nghi và tính kết nối cũng quan trọng.",
        "Ý chính",
      ),
      question(
        "fl22",
        "What does the example of a pavement ending at a junction illustrate?",
        [
          "The need for more parking",
          "The importance of connected routes",
          "The benefits of isolated improvements",
          "The preference for driving short distances",
        ],
        1,
        "Ví dụ cho thấy tuyến đi bộ phải liên tục, không chỉ đẹp ở một đoạn.",
      ),
      question(
        "fl23",
        "Why does the speaker mention a bench halfway to a park?",
        [
          "To recommend selling furniture",
          "To discourage older residents from walking",
          "To show that resting places have practical value",
          "To explain how parks earn money",
        ],
        2,
        "Chỗ nghỉ có thể giúp người lớn tuổi thực hiện được chuyến đi.",
      ),
      question(
        "fl24",
        "What might a pedestrian count fail to reveal?",
        [
          "Whether a street exists",
          "The number of people counted",
          "The location of a shop",
          "The experiences of people who avoid the route",
        ],
        3,
        "Đếm người đang đi không cho biết rào cản của người vẫn tránh tuyến đường.",
      ),
      question(
        "fl25",
        "How does the speaker view residents’ knowledge?",
        [
          "It complements technical assessment",
          "It makes all technical assessment unnecessary",
          "It is useful only for drawing maps",
          "It should be ignored if opinions differ",
        ],
        0,
        "Hiểu biết địa phương bổ sung cho đánh giá kỹ thuật, không thay thế hoàn toàn.",
        "Quan điểm người nói",
      ),
    ],
    7,
  ),
  listen(
    "full-listen-13",
    "Using evidence in everyday decisions",
    "Part 3 · Bài nói 2",
    `We encounter numerical claims every day. A product is described as twice as effective, a service advertises a dramatic improvement, or a headline announces that a new habit changes people's lives. Such claims are not necessarily false, but they often leave out information needed to interpret them. In this talk, I will suggest a few questions that help us become more careful readers of evidence.\n\nFirst, ask what is being compared. If a company says that its new process is fifty percent faster, faster than what? The comparison might involve an older version, a competing product or a situation in which no useful process existed at all. These are very different starting points. Without a clear baseline, even an accurate percentage may be difficult to use.\n\nSecond, consider the size and selection of the group being studied. A survey of people who already enjoy a service may produce more positive answers than a survey that also includes people who stopped using it. This does not mean the first survey is worthless. It means we should avoid assuming that its respondents represent everyone. The way participants are recruited can matter as much as the number who respond.\n\nThird, distinguish a relationship from an explanation. Suppose people who visit libraries frequently also report reading more books. It would be tempting to conclude that visiting a library causes people to read more. That may be part of the story, but people who already like reading may also be more likely to visit. Other factors, such as free time or access to books at home, could influence both behaviours. A simple association does not settle which explanation is correct.\n\nAnother useful question concerns what was actually measured. A learning application might report that users opened it on many consecutive days. That tells us something about repeated use, but not necessarily about understanding. To evaluate learning, we might need to know whether users can recall information later or apply it in a new situation. A convenient measurement should not automatically become the definition of success.\n\nIt is also important to notice uncertainty. A report that describes its limitations can be more useful than one that presents every result as certain. Limitations tell us where a conclusion is likely to apply and where more evidence is needed. They are not always signs of poor work; often they show that the researchers have considered alternative interpretations.\n\nFinally, careful reading does not require rejecting every claim. The aim is to match our confidence to the strength of the available evidence. Some decisions must be made before perfect information exists. In those cases, we can choose a reasonable option, observe what happens and revise our decision when better information becomes available. Being willing to update a view is a strength, not an admission that thinking carefully was pointless.`,
    [
      question(
        "fl26",
        "What does the speaker recommend checking first in a claim of improvement?",
        [
          "The colour of the advertisement",
          "The celebrity supporting the product",
          "The comparison being made",
          "The number of words in the headline",
        ],
        2,
        "Cần biết so với mốc nào; phần trăm tăng nhanh không tự có ý nghĩa.",
      ),
      question(
        "fl27",
        "Why may a survey of enthusiastic users be unrepresentative?",
        [
          "It excludes people who disliked or stopped using the service",
          "It necessarily contains no truthful answers",
          "It always includes too many participants",
          "It cannot ask about satisfaction",
        ],
        0,
        "Mẫu chỉ gồm người thích dịch vụ có thể bỏ qua người đã rời bỏ.",
      ),
      question(
        "fl28",
        "What does the library example demonstrate?",
        [
          "Libraries have no effect on reading",
          "An association does not establish a single causal explanation",
          "People who read never use libraries",
          "All surveys should be abandoned",
        ],
        1,
        "Mối liên hệ không khẳng định chiều nhân quả; sở thích sẵn có và yếu tố khác có thể tác động.",
      ),
      question(
        "fl29",
        "Why is opening a learning app daily an incomplete measure?",
        [
          "Daily use cannot be recorded",
          "It always reduces motivation",
          "It proves that the user has learned everything",
          "Repeated use does not necessarily demonstrate understanding",
        ],
        3,
        "Số ngày mở ứng dụng không tự chứng minh hiểu và vận dụng kiến thức.",
      ),
      question(
        "fl30",
        "What attitude does the speaker recommend toward uncertain evidence?",
        [
          "Reject every claim immediately",
          "Never change an initial decision",
          "Match confidence to evidence and remain willing to revise",
          "Wait for perfect information before any action",
        ],
        2,
        "Điều chỉnh mức tin theo bằng chứng và sẵn sàng cập nhật khi có thông tin tốt hơn.",
        "Quan điểm người nói",
      ),
    ],
    7,
  ),
  listen(
    "full-listen-14",
    "Designing useful community spaces",
    "Part 3 · Bài nói 3",
    `A community space may look impressive in photographs and still fail to become part of local life. A new room, courtyard or small park does not automatically create a community. What matters is whether people find reasons to use it and whether they feel that their presence is welcome. Today I will explore what makes a shared space useful over time.\n\nA sensible starting point is to observe existing activities. Before deciding what equipment to buy, organisers can ask how residents already spend time together and what prevents others from joining them. Perhaps older residents enjoy conversation but lack a shaded place to sit. Perhaps students need a quiet table in the afternoon, while parents need somewhere children can play safely. These needs may overlap, but they are not identical.\n\nTrying to accommodate every activity at the same moment can create conflict. A quiet reading group and an energetic music session are unlikely to work well side by side. Sometimes the answer is physical separation. In other cases, a simple timetable allows different groups to share the same area at different times. The timetable should be easy to understand and should leave some periods available for spontaneous use. If every hour is booked by an organised group, people who are not members may feel excluded.\n\nRules are another balancing act. Too few rules can leave users uncertain about noise, cleanliness or responsibility for equipment. Too many can make an informal gathering feel like a formal appointment. The most useful rules usually respond to problems that people recognise. Explaining the reason for a rule can encourage cooperation more effectively than displaying a long list of prohibitions.\n\nOrganisers should also think about who is missing. A meeting attended by confident regular users may suggest that everyone is satisfied, even though newcomers find the space difficult to enter. Asking people individually, providing a simple written feedback option and visiting at different times can reveal a wider range of experiences. No single method reaches every person, so a combination is often necessary.\n\nSmall experiments can reduce the risk of expensive mistakes. For example, movable tables can be tried in several arrangements before permanent furniture is installed. A temporary evening activity can reveal whether lighting, noise or transport creates difficulties. The purpose of a trial is not merely to prove that the original idea was good; it is to discover what should change.\n\nFunding is important, but ongoing care is equally necessary. Someone must arrange repairs, welcome new volunteers and notice when a regular activity stops meeting a need. These tasks may attract less attention than an opening ceremony, yet they often determine whether the space continues to matter. A successful community space should therefore be understood as a continuing relationship between people and a place, rather than as a completed construction project.`,
    [
      question(
        "fl31",
        "According to the speaker, what makes a community space successful?",
        [
          "Its appearance in promotional photographs",
          "How expensive its equipment is",
          "Whether it hosts a large opening ceremony",
          "Whether people use it and feel welcome",
        ],
        3,
        "Thành công dựa vào nhu cầu sử dụng thực tế và cảm giác được chào đón.",
        "Ý chính",
      ),
      question(
        "fl32",
        "Why should organisers observe existing activities before buying equipment?",
        [
          "To prevent any new activities",
          "To understand local needs and barriers",
          "To choose furniture only by price",
          "To avoid speaking with residents",
        ],
        1,
        "Quan sát và hỏi giúp biết nhu cầu cùng rào cản trước khi đầu tư.",
      ),
      question(
        "fl33",
        "Why should some time remain unbooked?",
        [
          "To allow informal use by people outside organised groups",
          "To reduce all community participation",
          "To ensure that the room stays empty",
          "To make the timetable harder to understand",
        ],
        0,
        "Khoảng thời gian không đặt trước giúp người không thuộc nhóm tổ chức vẫn sử dụng được.",
      ),
      question(
        "fl34",
        "What is the purpose of small experiments?",
        [
          "To guarantee that nothing will change",
          "To replace all long-term maintenance",
          "To discover improvements before making permanent investments",
          "To show that only one layout is possible",
        ],
        2,
        "Thử nghiệm nhỏ giúp phát hiện điều cần sửa trước khi đầu tư cố định.",
      ),
      question(
        "fl35",
        "What is the speaker’s final view of a community space?",
        [
          "It is complete after the opening ceremony",
          "It is successful whenever funding is sufficient",
          "It should be designed only for regular users",
          "It requires an ongoing relationship and continuing care",
        ],
        3,
        "Kết luận: đây là mối quan hệ liên tục giữa người và nơi chốn, cần chăm sóc dài hạn.",
        "Quan điểm người nói",
      ),
    ],
    6,
  ),
];
export const fullExamLessons = [...fullReading, ...fullListening];
export const allLessons = [...lessons, ...fullExamLessons];
